{{- range $key, $val := .Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - namespace: tenant01
        url: https://kubernetes.default.svc
      - namespace: tenant02
        url: https://kubernetes.default.svc
      - namespace: tenant03
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-apps-of-apps'
    spec:
      project: default
      source:
        path: apps-of-apps
        repoURL: https://github.com/lucasafonsokremer/k8s-setup-argocd-apps-of-apps.git
        targetRevision: HEAD
        helm:
          releaseName: apps-of-apps
          valueFiles:
            - values.yaml
            - values-{{"{{"}}namespace{{"}}"}}.yaml
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'
---      
{{- end }}
{{- end }}